[project]
name = "aabd-mock-azterketa-64153"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = ["numpy", "pandas", "matplotlib", "scikit-learn", "pydantic", "pytest", "nbformat", "nbclient", "ipykernel"]

[dependency-groups]
security = ["pip-audit"]

[tool.ruff.lint.isort]
known-first-party = ["mock_azterketa"]
