# Worker config (PDF 4.2). Aldagaiak ingurunetik: BOOTSTRAP, PLUGIN_PATH.
bootstrap.servers=${BOOTSTRAP}
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true
offset.storage.file.filename=/tmp/connect.offsets
plugin.path=${PLUGIN_PATH}
rest.port=8083
