# MongoDB sink (PDF 4.3 bide osoa). URIa ingurunetik.
name=mongodb-sink
connector.class=com.mongodb.kafka.connect.MongoSinkConnector
tasks.max=1
topics=iabd-retail_db-categories
connection.uri=${MONGO_URI}
database=retail_sink
collection=categories
