# MySQL source (PDF 4.1/4.2). Kredentzialak ingurunetik, ez fitxategian.
name=mysql-source
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.url=${MYSQL_JDBC_URL}
connection.user=${MYSQL_USER}
connection.password=${MYSQL_PASSWORD}
table.whitelist=categories
mode=incrementing
incrementing.column.name=category_id
topic.prefix=iabd-retail_db-
poll.interval.ms=5000
