bootstrap.servers=kafka:29092
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true
offset.storage.file.filename=/var/lib/kafka-connect/source.offsets
offset.flush.interval.ms=1000
plugin.path=/usr/share/java,/usr/share/confluent-hub-components
listeners=http://0.0.0.0:8083
rest.advertised.host.name=connect
rest.advertised.port=8083
config.providers=file
config.providers.file.class=org.apache.kafka.common.config.provider.FileConfigProvider
