name=mysql-source
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.url=jdbc:mysql://mysql:3306/retail_db?useSSL=false&allowPublicKeyRetrieval=true
connection.user=iabd
connection.password=${file:/opt/kafka-connect/private/mysql.properties:password}
table.whitelist=categories
mode=incrementing
incrementing.column.name=category_id
topic.prefix=iabd-retail_db-
poll.interval.ms=1000
