input { stdin {} }
filter {
  grok {
    match => { "message" => [
      "^%{IP:bezero_ip} %{WORD:metodoa} %{URIPATH:request} %{NUMBER:status_code} %{NUMBER:bytes}$",
      "^%{IP:bezero_ip} %{WORD:metodoa} %{URIPATH:request} %{NUMBER:status_code} %{NUMBER:bytes} %{GREEDYDATA:erabiltzailea}$",
      "^(?<data>%{YEAR}-%{MONTHNUM}-%{MONTHDAY}) %{IP:bezero_ip} %{WORD:metodoa} %{URIPATH:request} %{NUMBER:status_code} %{NUMBER:bytes}$"
    ] }
  }
}
output { stdout { codec => json_lines } }
