input { stdin {} }
filter {
  grok { match => { "message" => "^(?<timestamp>%{MONTHDAY}/%{MONTH}/%{YEAR}:%{TIME}) %{IP:bezero_ip} %{WORD:metodoa} %{URIPATH:request} %{NUMBER:status_code}$" } }
  if "_grokparsefailure" not in [tags] {
    date {
      match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss" ]
      locale => "en"
      timezone => "Europe/Madrid"
      target => "@timestamp"
    }
  }
}
output { stdout { codec => json_lines } }
