input { stdin { codec => json } }
filter {
  mutate {
    convert => { "status_code" => "integer" "bytes" => "integer" }
    rename => { "request" => "uri" }
    remove_field => [ "message" ]
  }
}
output { stdout { codec => json_lines } }
