input { stdin {} }
filter {
  grok {
    match => { "message" => "^(?<timestamp>%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{TIME}) %{LOGLEVEL:maila} %{WORD:zerbitzua} '%{DATA:mezua}' client=%{IP:bezero_ip}$" }
  }
  if "_grokparsefailure" not in [tags] {
    date {
      match => ["timestamp", "yyyy-MM-dd HH:mm:ss"]
      timezone => "Europe/Madrid"
    }
  }
}
output { stdout { codec => json_lines } }
